# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-18 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('A', 'Accesories'), ('SP', 'Speaker'), ('S', 'Synch')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('D', 'danger'), ('S', 'secondary')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
