# Generated by Django 2.2.8 on 2020-01-20 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_auto_20200120_0003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
