# Generated by Django 2.2.8 on 2020-01-26 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='active',
        ),
        migrations.AlterField(
            model_name='productreview',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ecommerce.Item'),
        ),
    ]
